### ISSUE TITLE
SPRINT 1: initial setup

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/gig-pact#1]
# sprint 1

## time frame
fri 29th Dec - fri  5th Jan

# related user stories
- N/A

# tasks
- [ ] create github repo
- [ ] create issue and sprint templates
- [ ] setup initial project structure
- [ ] start learning react native (https://galaxies.dev/react-native-path)
- [ ] design database
- [ ] decide between SQL or noSQL
- [ ] create initial list of most appropriate stack, libraries etc to use
